name: SQLiteLib
main: com.pablo67340.SQLiteLib.Main.SQLiteLib
version: 1.3
api-version: '1.20'
author: pablo67340
description: Plugin for any server.
commands:
  sqlite:
    description: Root SQLiteLib command.
    aliases: [sl]
permissions:
  sqlite.use:
    description: Allows usage to use SQLiteLib commands.